FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY CoolCat ./CoolCat/

WORKDIR /app/CoolCat
RUN dotnet restore

RUN dotnet publish -c Release -o out

# ±‡“ÎDockeræµœÒ
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app/CoolCat
COPY --from=build-env /app/CoolCat/out .
ENV ASPNETCORE_URLS http://0.0.0.0:5000
ENTRYPOINT ["dotnet", "Mystqiue.dll"]